# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 350
PLAYER_SPEED = 250
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_IMAGE = "XWing.png"

# Shots
SHOT_RADIUS = 5

# Asteroids
ASTEROID_MIN_RADIUS = 15
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE_SECONDS = 2.5
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_IMAGE = "Asteroid.png"

# Draw
LINE_WIDTH = 2
